databases:
  - name: clinica-juridica-db
    plan: free
    user: clinica_user
    databaseName: clinica_juridica
    region: oregon

services:
  - type: web
    name: proyecto-db-backend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: clinica-juridica-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: clinica-juridica-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: clinica-juridica-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: clinica-juridica-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: clinica-juridica-db
          property: password
